### ISSUE TITLE
A little concept error on the timeline

### ISSUE THREAD

**Issue by Gascon95** [boguz/SWCanonTimeline#1]
Hello there!

I'm a huge SW fan and I'm pretty updated on everything related to the saga and the new canon. I would like to contribute in this timeline with everything I know adding new entries on it whenever I can, but first of all I have to note a little concept error on it.

Officially, the "BBY/ABY" terminology is not used on the new canon, it's just something from the Legends continuity that it's like "deprecated". The new canon have no oficial terminology, so they just point out the number of years to the nearest movie. For example, the Obi-Wan and Anakin comic book series takes place 3 years before The Phantom Menace. To sum up, there's no "year 0", so you cannnot take the Battle of Yavin as such.

If you ant to use it anyway, I would souggest to add a caption with the meaning of BBY and ABY, cause newbies will not know it's meaning. :)

**Comment by boguz** [comment]
that is a good point. i had thought to put a info button on the upper left corner to talk about things like the meanings of the colors,... So maybe there there could also be some information about the terminology. in the [Wookeepedia's timeline](http://starwars.wikia.com/wiki/Timeline_of_canon_media) they have some kind of Years, but i'm not sure which...

But actually i have gotten a lot of "negative feedback" about this project, so i'm not sure i'll continue this. Or maybe at least not until i rethink the whole thing.
Do you think a Timeline like this makes sense?

**Comment by Gascon95** [comment]
The info in the wikipedia timeline takes The Phantom Menace as year 0, but I think that's not official, they just did it to have some start point. BTW, Obi-Wan & Anakin takes place 3 years after TPM, I've made a mistake earlier haha

Regarding the negative feedback... Well, I'm an administrator in two SW spanish forums, and I can assure you a Canon Timeline would be much usefull, cause even 3 years after the rebot, there's a lot of people that don't know which comics, novels, vieogames etc are part of the new canon and which ones belong to the Legends continuity. I think it could be great to participate in this project and I would contribute with everything I can in relation to SW and, if needed, with the source code.

**Comment by wynro** [comment]
I think it's a nice and visual way to introduce newcomers to the timeline without without having them read a 100 pages document about the complexities of it.  Of course, in topics like this you are always going to found people who disagree with you, like our friend @Gascon95. You shouldn't get yourself discouraged by them.

**Comment by Gascon95** [comment]
Hey, I'm not ddisagreeing, I'm just pointing out that the terminology used is not the official one for the new canon, which doesn't mean it's necessarily wrong.

**Comment by boguz** [comment]
that is great to hear. Then let's keep going!   =)

There is in the root folder a file called [info.md](https://github.com/boguz/SWCanonTimeline/blob/master/info.md) which contains the media i was planning to add to the Timeline.

Then inside each Element i would add a little description, like a paragraph or so, (like in the example already live on the site) and then a button with a like to some more info, possibly even to where you can buy it also.

Would you add anything? Take something away? Change something?

**Comment by Gascon95** [comment]
I'll take a look to the list later, but it looks quite complete.

About the description for each element, I would take it from the Wookieepedia, since almost everything have a bio on it. There's usually a first paragraph with a description, so I think the best thing to do is to take that paragraph and use it as the description of the element. The "more info" button, I think the best would be to set a link to the Wookieepeia bio of the element, cause is the most complete encyclopedia you will find on the Internt.

You could add another button if you like to link to some websites where you could buy the element you are reading about :)

**Comment by boguz** [comment]
yes, that is what i have done, i have taken it from Wookeepedia and also linked it to their article.   ;)

I will also start a "design ideas" issue, to address some concerns i have. would be great to have your input.   ;)

**Comment by Gascon95** [comment]
Sure. You can close this issue if you want :)
