### ISSUE TITLE
Design ideas

### ISSUE THREAD

**Issue by boguz** [boguz/SWCanonTimeline#3]
I have heard from several people that the "elements" are too big. Maybe instead of such a big "stripe" for each element on the list we should use smaller elements, maybe even something like a grid or more than one element per row.

I quite like it like this, but i can understand that when we have a lot of elements on the Timeline it will get long and maybe difficult to find information.

What do you think?

**Comment by Gascon95** [comment]
Well, first of all, let's clarify what we understand for an "element". You mean, by element, every entrance in the timeline, like "The Phantom Menace"?

If it's that way, as you say, it'll become a little annoying when the timelime becomes bigger.

I think it could be interesting to use, inside every year dropdown stripe, another bunch of dropdown rows, each of them showing just the tittle, the icon and type of element when compacted, and all the info, just like now, when clicked.

I don't know if I have been clear, it's difficult to explain things like these just with text haha I'll try to show it with an example:

- 32 BBY
    - The Phantom Menace [Icon] "Movie" (Compacted/folded)
    - Another element [Icon] "Type" (Compacted/folded)
                                      ...
                                      ...

Now, unfolded:

- 32 BBY
   - The Phantom Menace [Icon] "Movie" (Unfolded, just like it's now)
      [Description]
      More info button
   - Another element.... (Compacted or unfolded, depending on if it's been clicked)

**Comment by boguz** [comment]
that sounds like a good idea!

**Comment by Gascon95** [comment]
BTW, I found this while looking around on Google:

https://github.com/twainisalive/starwarscanontimeline

It's both the same and a different thing compared with what you have in mind here. On the one hand, well, is a canon timeline, with a nice design, search filter etc So, a nice web. But, on the other hand, here anyone can contribute to the timeline adding new elements (comic series, novels, animated series etc), unlike on that web, that only the admin can add and update the content. I think thats a pro.

Besides, here the idea is much simpler: we only provide a minimalist timeline with a small description of each element. If anyone want to know more, they can go straight to the wookieepedia, were there is a lot of detailed info. In that timeline, there are specific bios for every entry (every movie, comic book issue etc).

I would go on with this, but the decision is up to you :)

**Comment by boguz** [comment]
ah, that looks nice.
Filter will also be possible on our timeline, but i'm not planning on making so that everyone can add new things...

**Comment by Gascon95** [comment]
Well, I meant that cause anyone can make a pull request here on github adding new info, not through a funtionality on the site :)

I've asked some people on a SW whatsapp fan group and they like the idea of being able of hiding or showing the info you are not interested in. The only con (for now) is that it's now responsive for mobile phone browsers haha

**Comment by boguz** [comment]
yes, i also think choosing what you want to see is a good feature, and not difficult to make.

But i think i will also make the "events" a bit smaller. I'm not so happy with this design...

**Comment by Gascon95** [comment]
Sure, go ahead. I'll be filling the site with the info of the timeline :)

Oh, and BTW, I thought the idea was to make just 1 stripe per year. I mean, if we have more than one element in a year (for example, a comic book, a novel and a video game), there should be just 1 stripe for that year and muliple stripes inside, one for each element. Just and idea, I thinks that makes the site more usable ;)
